Update github-pages.yml
Update the github action to build and publish docs automatically.

diff --git a/.github/workflows/github-pages.yml b/.github/workflows/github-pages.yml
--- a/.github/workflows/github-pages.yml
+++ b/.github/workflows/github-pages.yml
@@ -11,28 +11,42 @@ jobs:
     # Checks-out the repository 
     - uses: actions/checkout@v2
       
-    # Builds the sphinx docs
-    - uses: ammaraskar/sphinx-action@master
+    - uses: goanpeca/setup-miniconda@v1
       with:
-        build-command: "make html"
-        docs-folder: "docs/"
+        auto-update-conda: true
+        python-version: ${{ matrix.python-version }}
+#         activate-environment: scrud-django
+#         environment-file: environment-dev.yml
+#         channels: conda-forge
+    - name: Conda install
+      shell: bash -l {0}
+      run: conda install sphinx    
     
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/openteamsinc/semantic-http-spec.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.SEMANTIC_HTTP_SPEC_KEY }}
+    - name: Build docs
+      shell: bash -l {0}
+      run: make html
+#     # Builds the sphinx docs
+#     - uses: ammaraskar/sphinx-action@master
+#       with:
+#         build-command: "make html"
+#         docs-folder: "docs/"
+    
+#     # Publish built docs to gh-pages branch.
+#     # ===============================
+#     - name: Commit documentation changes
+#       run: |
+#         git clone https://github.com/openteamsinc/semantic-http-spec.git --branch gh-pages --single-branch gh-pages
+#         cp -r docs/_build/html/* gh-pages/
+#         cd gh-pages
+#         git config --local user.email "action@github.com"
+#         git config --local user.name "GitHub Action"
+#         git add .
+#         git commit -m "Update documentation" -a || true
+#         # The above command will fail if no changes were present, so we ignore
+#         # that.
+#     - name: Push changes
+#       uses: ad-m/github-push-action@master
+#       with:
+#         branch: gh-pages
+#         directory: gh-pages
+#         github_token: ${{ secrets.SEMANTIC_HTTP_SPEC_KEY }}
